/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  CalimeroApp,
  Context,
} from '@calimero-network/calimero-client';

// Generated types

export interface Like {
  user_id: string;
  user_name: string;
  timestamp: number;
}

export interface Post {
  id: string;
  author_id: string;
  author_name: string;
  author_avatar: string;
  content: string;
  timestamp: number;
  likes: Like[];
  tips: Tip[];
  author_wallet_address: string | null;
}

export interface Tip {
  user_id: string;
  user_name: string;
  amount_usdc: string;
  timestamp: number;
  tx_hash: string;
}

export interface User {
  id: string;
  name: string;
  avatar: string;
  bio: string;
  wallet_address: string | null;
}










export type AbiEvent =
  | { name: "UserCreated" }
  | { name: "UserUpdated" }
  | { name: "PostCreated" }
  | { name: "PostLiked" }
  | { name: "PostUnliked" }
  | { name: "PostDeleted" }
  | { name: "TipSent" }
  | { name: "UserFollowed" }
  | { name: "UserUnfollowed" }
;


/**
 * Utility class for handling byte conversions in Calimero
 */
export class CalimeroBytes {
  private data: Uint8Array;

  constructor(input: string | number[] | Uint8Array) {
    if (typeof input === "string") {
      // Hex string
      this.data = new Uint8Array(
        input.match(/.{1,2}/g)?.map((byte) => parseInt(byte, 16)) || []
      );
    } else if (Array.isArray(input)) {
      // Number array
      this.data = new Uint8Array(input);
    } else {
      // Uint8Array
      this.data = input;
    }
  }

  toArray(): number[] {
    return Array.from(this.data);
  }

  toUint8Array(): Uint8Array {
    return this.data;
  }

  static fromHex(hex: string): CalimeroBytes {
    return new CalimeroBytes(hex);
  }

  static fromArray(arr: number[]): CalimeroBytes {
    return new CalimeroBytes(arr);
  }

  static fromUint8Array(bytes: Uint8Array): CalimeroBytes {
    return new CalimeroBytes(bytes);
  }
}

/**
 * Convert CalimeroBytes instances to arrays for WASM compatibility
 */
function convertCalimeroBytesForWasm(obj: any): any {
  if (obj === null || obj === undefined) {
    return obj;
  }

  if (obj instanceof CalimeroBytes) {
    return obj.toArray();
  }

  if (Array.isArray(obj)) {
    return obj.map(item => convertCalimeroBytesForWasm(item));
  }

  if (typeof obj === "object") {
    const result: any = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = convertCalimeroBytesForWasm(value);
    }
    return result;
  }

  return obj;
}

/**
 * Convert arrays back to CalimeroBytes instances from WASM responses
 */
function convertWasmResultToCalimeroBytes(obj: any): any {
  if (obj === null || obj === undefined) {
    return obj;
  }

  if (Array.isArray(obj) && obj.every(item => typeof item === "number")) {
    return new CalimeroBytes(obj);
  }

  if (Array.isArray(obj)) {
    return obj.map(item => convertWasmResultToCalimeroBytes(item));
  }

  if (typeof obj === "object") {
    const result: any = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = convertWasmResultToCalimeroBytes(value);
    }
    return result;
  }

  return obj;
}

export class AbiClient {
  private app: CalimeroApp;
  private context: Context;

  constructor(app: CalimeroApp, context: Context) {
    this.app = app;
    this.context = context;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this.app.execute(this.context, 'init', {});
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * create_user
   */
  public async createUser(params: { name: string; avatar: string; bio: string; public_key: string; wallet_address: string | null }): Promise<User> {
    const response = await this.app.execute(this.context, 'create_user', params);
    if (response.success) {
      return response.result as User;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_user_by_public_key
   */
  public async getUserByPublicKey(params: { public_key: string }): Promise<User> {
    const response = await this.app.execute(this.context, 'get_user_by_public_key', params);
    if (response.success) {
      return response.result as User;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * check_public_key_registered
   */
  public async checkPublicKeyRegistered(params: { public_key: string }): Promise<boolean> {
    const response = await this.app.execute(this.context, 'check_public_key_registered', params);
    if (response.success) {
      return response.result as boolean;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_user
   */
  public async getUser(params: { id: string }): Promise<User> {
    const response = await this.app.execute(this.context, 'get_user', params);
    if (response.success) {
      return response.result as User;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_all_users
   */
  public async getAllUsers(): Promise<User[]> {
    const response = await this.app.execute(this.context, 'get_all_users', {});
    if (response.success) {
      return response.result as User[];
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * update_user
   */
  public async updateUser(params: { user_id: string; name: string; bio: string; wallet_address: string | null }): Promise<User> {
    const response = await this.app.execute(this.context, 'update_user', params);
    if (response.success) {
      return response.result as User;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * create_post
   */
  public async createPost(params: { author_id: string; content: string }): Promise<Post> {
    const response = await this.app.execute(this.context, 'create_post', params);
    if (response.success) {
      return response.result as Post;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_all_posts
   */
  public async getAllPosts(): Promise<Post[]> {
    const response = await this.app.execute(this.context, 'get_all_posts', {});
    if (response.success) {
      return response.result as Post[];
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_post
   */
  public async getPost(params: { id: string }): Promise<Post> {
    const response = await this.app.execute(this.context, 'get_post', params);
    if (response.success) {
      return response.result as Post;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * delete_post
   */
  public async deletePost(params: { post_id: string; user_id: string }): Promise<void> {
    const response = await this.app.execute(this.context, 'delete_post', params);
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * like_post
   */
  public async likePost(params: { post_id: string; user_id: string }): Promise<Post> {
    const response = await this.app.execute(this.context, 'like_post', params);
    if (response.success) {
      return response.result as Post;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * unlike_post
   */
  public async unlikePost(params: { post_id: string; user_id: string }): Promise<Post> {
    const response = await this.app.execute(this.context, 'unlike_post', params);
    if (response.success) {
      return response.result as Post;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * check_user_liked_post
   */
  public async checkUserLikedPost(params: { post_id: string; user_id: string }): Promise<boolean> {
    const response = await this.app.execute(this.context, 'check_user_liked_post', params);
    if (response.success) {
      return response.result as boolean;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * record_tip
   */
  public async recordTip(params: { post_id: string; user_id: string; amount_usdc: string; tx_hash: string }): Promise<Post> {
    const response = await this.app.execute(this.context, 'record_tip', params);
    if (response.success) {
      return response.result as Post;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_post_count
   */
  public async getPostCount(): Promise<number> {
    const response = await this.app.execute(this.context, 'get_post_count', {});
    if (response.success) {
      return response.result as number;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * follow_user
   */
  public async followUser(params: { follower_id: string; followee_id: string }): Promise<void> {
    const response = await this.app.execute(this.context, 'follow_user', params);
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * unfollow_user
   */
  public async unfollowUser(params: { follower_id: string; followee_id: string }): Promise<void> {
    const response = await this.app.execute(this.context, 'unfollow_user', params);
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * is_following
   */
  public async isFollowing(params: { follower_id: string; followee_id: string }): Promise<boolean> {
    const response = await this.app.execute(this.context, 'is_following', params);
    if (response.success) {
      return response.result as boolean;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_followers
   */
  public async getFollowers(params: { user_id: string }): Promise<string[]> {
    const response = await this.app.execute(this.context, 'get_followers', params);
    if (response.success) {
      return response.result as string[];
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_following
   */
  public async getFollowing(params: { user_id: string }): Promise<string[]> {
    const response = await this.app.execute(this.context, 'get_following', params);
    if (response.success) {
      return response.result as string[];
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_follower_count
   */
  public async getFollowerCount(params: { user_id: string }): Promise<number> {
    const response = await this.app.execute(this.context, 'get_follower_count', params);
    if (response.success) {
      return response.result as number;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_following_count
   */
  public async getFollowingCount(params: { user_id: string }): Promise<number> {
    const response = await this.app.execute(this.context, 'get_following_count', params);
    if (response.success) {
      return response.result as number;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

}